name: Build and Deploy Next.js site

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  BASE_PATH: 'THE Project Files/final-version/geeks-v-3'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: |
          cd ${{ env.BASE_PATH }}
          yarn install --frozen-lockfile

      - name: Build
        run: |
          cd ${{ env.BASE_PATH }}
          yarn build

      - name: Export
        run: |
          cd ${{ env.BASE_PATH }}
          yarn export

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ${{ env.BASE_PATH }}/out
